### ISSUE TITLE
error on the read in

### ISSUE THREAD

**Issue by jkreinz** [petrelharp/local_pca#10]
I'm using the stand-alone R script (although the same issue arises using the R package) to run local PCAs on windows across single scaffold in my genome with the command:

`Rscript run_lostruct.R -i . -t bps 1000 -I sampleinfo`

I get the following error immediately on the read in:
`Finding PCs for ... and writing out to ...pca.csv and ...csv
Taking input= as a system command ('bcftools query -f '%CHROM\t%POS\n' /ohta/julia.kreiner/waterhemp/data/fixed_assembly/reveal_psuedoassembly/TSR_work/lostruct/Scaffold_11_qualdpmissing.bcf') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure envionment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.`

Thanks!

**Comment by petrelharp** [comment]
Thanks for the report! I had not seen this yet.

This can be safely ignored: see the discussion at https://github.com/Rdatatable/data.table/blob/master/NEWS.md .  You can turn it off by setting, in your code, `options(datatable.fread.input.cmd.message=FALSE)`. I might be able to disable the warning; we'll see what I can do.

**Comment by petrelharp** [comment]
I have added this option to the `run_lostruct.R` script [on github](https://github.com/petrelharp/local_pca/commit/dd69f26b0f6424cadb34a2d19a07cc109b6f8c79)
