### ISSUE TITLE
NA values in PCA and MDS results

### ISSUE THREAD

**Issue by jdmanthey** [petrelharp/local_pca#11]
Dear Dr. Ralph,

I am attempting to run your lostruct program, and it appears that it is working. However, I am getting a large portion of windows with NA values in the PC and MDS output (up to 30% of windows on a chromosome). At first, I thought this may be because I was using 50kbp windows and there wasn't enough variation in some windows, but I still get a few NA values even when using the program with windows of 10,000 SNPs. I am using a dataset that has no missing data and 22 individuals. I am running these analyses using the templated directory method and the command line. 

Any thoughts on what may be causing these results or what I could do to troubleshoot?

Thanks,
Joe Manthey

**Comment by jdmanthey** [comment]
I believe I figured out the answer to the problem. If there is phasing information in the genotype, e.g., a genotype of 0|1 instead of 0/1, then the program does not recognize the data and NA values appear. Once I replaced all the | with / in the vcf files before converting to bcf, the problem disappeared and I had no more NA values in the PCA output tables.

**Comment by petrelharp** [comment]
Hm, that's odd. Can you pull out the genotype matrix for one of the troublesome windows and look at it?

**Comment by petrelharp** [comment]
Hm, strange - the `vcf_query( )` function is *supposed* to deal with either phased or unphased formats. Unless your VCF files are a mix of both phased and unphased data? The function infers which format using the first 100 lines.  If you can provide a small example VCF file that reproduces the problem, I'd be happy to fix it.

**Comment by jdmanthey** [comment]
I was running the analyses on my workstation at the office, so I will send you an example some time tomorrow. The data I had that wasn't working was GATK 4.1.0 output that include both phased and unphased genotypes depending on available information for each position.

**Comment by petrelharp** [comment]
Ah-ha - I didn't think about that possibility.  I've pushed a fix that should be able to read your data without modification - let me know (and re-open this issue) if not?  Thanks for the report!

**Comment by siv-n** [comment]
Hello! I've run lostruct on a dataset that was variantcalled with GATK v4.4.0.0, and believe I'm encountering the same issue as I see a lot of NAs in my pca.csv files. Ive ran lostruct via the templated version (using run_lostruct.R). My R package seems up to date in R. I saw that the code for vcf_query() was updated to deal with the mix of phased and unphased genotypes, but I'm not sure how to use that code in the templated version. Any tips on how to do this?  Thanks in advance for help, and for the great program!

**Comment by petrelharp** [comment]
I think (but haven't double-checked) that the templated version already does use `vcf_query`. Could you perhaps verify that this is indeed the problem (e.g., by making a small example VCF; showing it has unexpeted NAs; changing the VCF to not have mixed phased/unphased; and showing the problem goes away? This should be quick and would be the first step in fixing this.
