### ISSUE TITLE
Questions regarding bcftools

### ISSUE THREAD

**Issue by HanXiaoEvo** [petrelharp/local_pca#18]
Hi everyone,

I am highly interested in local PCA but got to a bit hesitant of installing bcftools on my windows 8. 

I have never done any bioinformatics on my windows therefore I am wondering if it matters to have the Linux/python environment first or I can just install it? Thank you very much if you can help me with this super naive question!

Best regards,
Han Xiao

**Comment by petrelharp** [comment]
Hello, and welcome! This is a good question. Unfortunately, I suspect that even if you have bcftools installed, the way that the R package calls bcftools will not work on Windows. I don't know, because I haven't tried it, and don't have the resources to make that work at the moment. (help appreciated, if anyone else does, though!)  Everything *should* work on linux/unix or on macOS.

You would still be able to use some of the functions in the R package if you can load the genotype information into R some other way. The advantage to using bcftools is that it does not require the entire dataset to be loaded into memory at once. 

You also mention python: this package doesn't use python at all, but there is a prototype python version: https://github.com/jguhlin/lostruct-py .

Does this answer your question?

**Comment by HanXiaoEvo** [comment]
Thank you very much for your super quick reply!

I see, so the point is just to load the file, for example, in my case, it can be a vcf file (I have plink and genpop output but these seem not supported), is it OK to use any other functions to read in?  Actually  I am not working on a super large data set as the SNPs were generated by ddRAD pair-end reads, 151 for each. Then I think maybe even to read all the data in is not a problem. Another question is, as it is still a PCA method, I assume no LD should be there so I should write single SNP for each locus rather than calling for all, right?  By the way my reference genome is a draft and not into chromosomes, will it work OK? 

I was a bit confused that you mentioned in the tutorial that recodes data should be imported as numeric, will it be done by eigen_windows()? I will try using another package to read in first, but if not, do you think it is better to run R in Linux? What is the lowest version of R needed then? Our Linux R is quite out of fashion.

Thank you very much for your quick reply and hopefully, I can run it for my work!

Cheers,
Han

**Comment by petrelharp** [comment]
Hm: have you looked at the [quick example](https://github.com/petrelharp/local_pca/blob/master/popres/popres_example.R)? It reads in data from plink (as a tped), using the `read_tped` function in this package, which returns a numeric matrix. If you have data in plink format, you should be able to modify that example; if not, then you just need to get your data into a numeric matrix *somehow* (that looks like a tped file, as `chr22` is in that example), and then you can apply `eigen_windows` to it.

> Another question is, as it is still a PCA method, I assume no LD should be there so I should write single SNP for each locus rather than calling for all, right? By the way my reference genome is a draft and not into chromosomes, will it work OK?

I definitely recommend *not* pruning SNPs for LD: local PCA is specificlaly looking for local information, which will be easier to see with linked SNPs present.   I hope your loci are mapped to a reasonable (chromosome-scale) reference?

>  What is the lowest version of R needed then? 

I'm not sure - I don't think it relies on a particularly recent version!

**Comment by HanXiaoEvo** [comment]
OK I will then check about using plink output!

Well the genome is claimed as chromosome level....here is the link: https://www.ncbi.nlm.nih.gov/assembly/GCF_002910315.2
So I think I should write all SNPs on the loci right, which is like to do a haplotype scale PCA? But then if the local pca is somehow related to LD calculation? Sry that I haven't get time to get through the whole paper (specially the methods part) but I will do it ASAP!

Cheers,
Han
