### ISSUE TITLE
chromosome names gives me problems

### ISSUE THREAD

**Issue by siv-n** [petrelharp/local_pca#27]
Hi, 

thanks for this awesome tool! We have tried it on our datasets and find it very useful.
I am currently trying to run lostruct on a dataset that has the first nine chromosomes named as so: 01, 02, 03 etc, and this seems to give me some issues. I think it's the naming of the chromosomes that's giving me problems, as it worked fine for chromosomes 10 and onwards. but not entirely sure ..

I'm running the templated, the run_lostruct.R script. 
The issue seems to appear when or before the program tries to generate the pca.csv file, as it turns out full of NAs. I had a look in the regions.csv file, and see there that the name of the chromosome in the "chrom" column turns out "1" rather than "01" etc. 

Any help/insight on what might be the issue and solution would help me greatly.
thank you so much!

all the best
Siv H

**Comment by petrelharp** [comment]
Hm, sorry to hear it. Does it give any error messages? Might you be able to
paste here a very small example of your input files, eg the top 20 lines of
chromosome 01?

**Comment by siv-n** [comment]
thanks for the quick answer. I use vcf files per chromosome as input,  and for the first 1-9 chromosomes i run the command as so in a slurm script: ./run_lostruct.R -i data_chr0${SLURM_ARRAY_TASK_ID}/ -t snp -s 100 -m 4

where data_chr0${SLURM_ARRAY_TASK_ID} are directories with vcfs and their index files. 

here is the error I get in the slurm output:
```
`Warning message:
No sample information file - report from summarize_run.Rmd won't have colors. 
Finding PCs for chromosome chr1 in file *scf_01_raw_*_filtered.vcf.gz and writing out to lostruct_results/type_snp_size_100_weights_none_jobid_037296/chr1.pca.csv and lostruct_results/type_snp_size_100_weights_none_jobid_037296/chr1.regions.csv 
Warning message:
In vcf_windower_snp(file = file, sites = sites, size = size, samples = samples) :
  Trimming from chromosome ends: 1: 7 SNPs.
Done finding PCs, computing distances.
   user  system elapsed 
 14.006   0.214  14.254 
Done computing distances, running MDS and writing results to lostruct_results/type_snp_size_100_weights_none_jobid_037296/mds_coords.csv 
Error in cmdscale(pc.distmat[!na.inds, !na.inds], k = opt$nmds) : 
  'k' must be in {1, 2, ..  n - 1}
Calls: cbind -> cmdscale
Execution halted`
```
The error it throws is for the computing of the MDS, but the real problem occurs earlier, as I inspected the pca.csv file, and find only NAs.. 

Here is what the chromosome names look like in the vcf header of input file:
```
##contig=<ID=01,length=..>
##contig=<ID=02,length=..>
##contig=<ID=03,length=..>
```

And here is the top of the chr1.regions.csv:
```
"chrom","start","end"
"1",13357,601557
"1",601566,675442
"1",675449,778991
```

best
Siv

**Comment by petrelharp** [comment]
Thanks very much for the nice report! The problem was that `fread::data.table( )` was automatically deciding that the "chromosome" column was numeric, and so dropping the leading 0's. I think I've fixed the problem - if you reinstall from github, it should work now. Let me know how it goes, and re-open this if the problem isn't solved!

**Comment by siv-n** [comment]
It works now! thanks for the help and being so quick.

best
Siv
