### ISSUE TITLE
error in reading VCF

### ISSUE THREAD

**Issue by ylevmirom** [petrelharp/local_pca#28]
Hello, first time I'm using lostruct. 

I'm trying to read a VCF file using this code after installing the package to R studio: 
`snps <- read_vcf("my_vcf.vcf.gz")`

and I'm getting this error: 

> > snps <- read_vcf("my_vcf.vcf.gz")
> |--------------------------------------------------|
> |==================================================|
> Error in dim(haps) <- c(2, dim(dips)) : 
>   dims [product 270590588] do not match the length of object [268886609]
> 

I also tried to convert the vcf to bcf like the example in the manual but still getting the same error. 

i would really appreciate some help, 

tnx

yael

**Comment by petrelharp** [comment]
Hm - I suppose this is something to do with the VCF. Could you provide a minimal working example? For instance, perhaps if you do `read_vcf( )` to the first 10 SNPs for the first 3 genomes then you get the error, and can just copy-paste the resulting very small VCF in to this issue?

**Comment by ylevmirom** [comment]
Hi Peter,
I actually used vcfR to read the vcf instead of data.table and it seems to
be working fine now.
thanks for your reply
Yael

**Comment by petrelharp** [comment]
Glad to hear it!
