### ISSUE TITLE
SNP filtering recommendations

### ISSUE THREAD

**Issue by sjfleck** [petrelharp/local_pca#30]
I'm working with a data set that we want to try Local_PCA with. I'm using a VCF file that was filtered by a collaborator, they used these filtering VCFtools options:

--remove-indels --max-missing 1 --minDP 5 --maxDP 500 --minGQ 30 --plink --mac 2 --remove-filtered-all

And they only kept the chromosome-level scaffolds. It resulted in 256,649 SNPs divided among the chromosomes. This is many fewer SNPs than I'm used to working with. In the past, I've had many more SNPs on a single chromosome than in this whole assembly. The chromsome with the most SNPs has 14,364 SNPs and the one with the fewest SNPs has 3,148 SNPs. Do you have any recommendations for filtering differently or if this is fine as is. 

I know the human data set also had a low number of SNPs and 100 SNPs/window was used. If I keep it as is, I'm assuming "-t snp -s 100" would work for 100 SNPs/Window like with the human dataset

Thanks for any help you can provide

**Comment by petrelharp** [comment]
The main consideration is that you've got "enough information" per window - i.e., if each window has enough SNPs (and SNPs at very low frequency carry less information). So, I'd not worry too much about filtering as long as you have enough for reasonable resolution. Of course, it can be hard to tell what 'enough' is, and it also depends on your goals. If what you're looking for are "big, obvious changes" (e.g., a big segregating inversion), then those changes should be reflected in basically all the SNPs and still show up just fine after filtering. If what you're looking for is reflected particularly in SNPs that got filtered out for some reason (eg an allele frequency filter), then that won't be great.

However, it looks like those filters are all designed to remove bad/uncertain genotypes, and singletons, which is a great idea and shouldn't systematically bias things. If you're surprised by the small number of SNPs, however, you should make sure all is as you expect - this is a low-diversity species or it's genotyping (not WGS) data, or something.

And, as with any visualization method, 'the proof is in the pudding': try it out, and if it shows you something interesting/sensible/unexpected then it's being useful.

**Comment by petrelharp** [comment]
I'm going to close this; feel free to re-open if your question isn't answered.
