### ISSUE TITLE
Error when I try to plot MDS

### ISSUE THREAD

**Issue by ltalignani** [petrelharp/local_pca#32]
Dear Peter,
I am working on Anopheles dataset and try to do a local PCA, using the great templated scripts. My first question is about the input files. Is it better to use a single BCF containing all the chromosomes, or one bcf file per chromosome?

The `run_lostruct.R` works perfectly and generates the `pca.csv`, `regions.csv`, `config.json` and `mds_coords.csv` files 
[config.json](https://github.com/petrelharp/local_pca/files/13294486/config.json)
[mds_coords.csv](https://github.com/petrelharp/local_pca/files/13294487/mds_coords.csv)
[Bwambae.AgamP4ROAST.flt.snp.inv.annot.pass.GQ20.norm.chr2L.HRUN.sort.norep.indflt70.genflt80.maf.regions.csv](https://github.com/petrelharp/local_pca/files/13294488/Bwambae.AgamP4ROAST.flt.snp.inv.annot.pass.GQ20.norm.chr2L.HRUN.sort.norep.indflt70.genflt80.maf.regions.csv)
[Bwambae.AgamP4ROAST.flt.snp.inv.annot.pass.GQ20.norm.chr2L.HRUN.sort.norep.indflt70.genflt80.maf.pca.csv](https://github.com/petrelharp/local_pca/files/13294489/Bwambae.AgamP4ROAST.flt.snp.inv.annot.pass.GQ20.norm.chr2L.HRUN.sort.norep.indflt70.genflt80.maf.pca.csv)

When I run the script from `summarize_run.Rmd`, 

`Rscript -e 'templater::render_template("summarize_run.Rmd",output="lostruct_results/type_snp_size_1000_weights_none_jobid_591404/run_summary.html",change.rootdir=TRUE)'`

I get two errors: 

The first is that the mds_pairplot-1.pdf is not generated

And the second error at step `# Plot corners and MDS along the chromosome`, and more precisely from line 177 and the function `chrom.plot` called. The output is 

`Error in xy.coords(x, y): 'x' and 'y' lengths differ `

Do you have any idea where the problem might be coming from? I'm also attaching the run_summaru.md because for some reason I can't attach the summary in html format.
[run_summary.md](https://github.com/petrelharp/local_pca/files/13294590/run_summary.md)

Best regards

**Comment by petrelharp** [comment]
Hm, interesting. The second error is because your `mds_coords.csv` file has twice as many entries as do the `.pca.csv` and `.regions.csv` files - is it possible that these were created with different settings (e.g., with a different window size)? I'd suggest starting in a clean directory and running `run_lostruct.R` again, to make sure?

I'm also guessing that fixing that error will fix the first problem (not producing `mds_pairplot-1.pdf`), but am not sure at all.

**Comment by ltalignani** [comment]
Thanks for your answer. 
I don't understand this mistake either. The results of the analysis were obtained in a directory created automatically without any intervention on my part.  We can now close this subject, as I have no further worries of this kind.

**Comment by ltalignani** [comment]
FYI, MDS results are written twice in succession for the same chromosome in `mds_coords.csv`. I haven't touched the run_lostruct.R script and have no idea what is causing the problem. I'm attaching the results directory as a link [https://filesender.renater.fr/?s=download&token=a73919c5-2801-4f07-80a9-0ae20dd855ba](url)

Edit : my data directory contained compressed vcf files and bcf files together. I think that's why the results were written twice.
