### ISSUE TITLE
cmdscale issue

### ISSUE THREAD

**Issue by owensgl** [petrelharp/local_pca#7]
I've been running lostruct based on the Medicago documentation. I have an issue where cmdscale won't run at a smaller SNP window size due to missing data, but I don't know how to get it to work around that. If I increase the window size it will work, so it has to do with windows that have too much missing data, I assume.

Here's my code: 
`
window_size <- 400`
`bcf.file <- paste(data_directory, "/", data_name,".bcf",sep="")`
`samples <- read_tsv(paste(data_directory, "/", data_name,".samplelist.txt",sep=""),col_names = F)`
`colnames(samples) <- c("sample")`
`sites <- vcf_positions(bcf.file)`
`win.fn.snp <- vcf_windower(bcf.file, size=window_size, type="snp", sites=sites) `
`system.time( snp.pca <- eigen_windows(win.fn.snp,k=2, mc.cores=10) )`
`system.time( pcdist <- pc_dist( snp.pca ) )`
`na.inds <- is.na( snp.pca[1,] )`
`k_kept <- 20`
`mds <- cmdscale( pcdist[!na.inds,!na.inds], eig=TRUE, k=k_kept )`

And the error message:
>  Error in cmdscale(pcdist[!na.inds, !na.inds], eig = TRUE, k = k_kept) : 
  NA values not allowed in 'd'
Any ideas?

**Comment by petrelharp** [comment]
Hm. I need some more information: where are the NAs coming in? Please find
out which entries of `pcdist[!na.inds,!na.inds]` are NA, and what the
corresponding rows of `snp.pca` look like.

**Comment by owensgl** [comment]
Investigating further, there are 259 windows (out of 10678) that have NA in the pcdist matrix. Looking at the PCAs in snp.pca, they are all "NA" in the eigenvectors. Looking at the SNPs in those windows, there are no samples with entirely missing data, but there's a half dozen with ~80% missing data, and it seems likely that they could entirely not overlap in their called SNPs. I could remove those sample entirely. Alternatively, if I know what windows aren't working, I think I could just remove them from the pcdist matrix? Does that make sense?

**Comment by petrelharp** [comment]
You've got the right idea. You should only get NA if two samples don't overlap at all (or with only one SNP maybe); but you should start to be suspicious if some have very little overlap. If your 80% missing samples have much more missing data than the others, I recommend removing them.

In that code snippet, indexing by `!na.inds` is supposed to remove these NA entries, but apparently it's not working in your case.  Something similar should get it to run, if you want to try with them included.

**Comment by owensgl** [comment]
Thanks for the advice. I'm pulling out the samples with missing data. They have distinctly lower coverage and I actually had forgotten that they were included. I'm optimistic about it working now!

**Comment by owensgl** [comment]
By removing the problem individuals, it fixed most of the NA windows, but there were still a few. I realized that the !na.inds statement wasn't working as intended.

In the Medicago example it is:
`na.inds <- is.na( snp.pca[1,] )`
I replaced it with:
`na.inds <- is.na(pcdist[,1]) `

This worked for me.

**Comment by petrelharp** [comment]
> ` na.inds <- is.na(pcdist[,1])`

Hah, whoops. Good catch. I see that I had fixed that bug in [a different example](https://github.com/petrelharp/local_pca/blob/master/sims/example/simple_example.Rmd). Sorry about that.

**Comment by coopergrace** [comment]
Hi Peter,

Apologies for resurrecting this issue, but I didn't want to open a new one with a very similar error!

`Error in cmdscale(pc.distmat[!na.inds, !na.inds], k = opt$nmds) : 
  NA values not allowed in 'd'`

Seems to ignore the exclusion of NAs, but if I exclude those rows myself, I then get issues with matching up the windows and the PCA results. 

Edit to add: I'm using the `run_lostruct.R` file from the `templated` folder.

I would appreciate your help!

**Comment by petrelharp** [comment]
Hi, @coopergrace - well, looking at `run_lostruct.R` the problem does not seem to be a result of the error we fixed above. So, I think the question is: where are the NAs in `pc.distmat[!na.inds, !na.inds]`, and what are the corresponding rows of `all.pcs`? (Things you should look out for is if there's so much missing data that there are pairs of individuals whose non-NA entries don't overlap at all.)

**Comment by coopergrace** [comment]
Hi Peter,

I'm working on a small eukaryote genome (32Mb), but there are very few rows with NAs - less than 1%. The individuals however are very different from one another, perhaps even different species. I suspect there are regions with very high conservation and others which are far more divergent (and thus SNP heavy).

Would it be problematic to combine the resulting `regions.csv` and `pca.cvs` files, omit the NA rows and perform the `cmdscale`? Or does the calculation need to use the dimensions of `all.pcs`?

Thanks

Cooper

**Comment by petrelharp** [comment]
Hm - I'm forgetting which are rows and which are columns, but: if you've got windows, or individuals, that are problematic in terms of having lots of missing data, it's not problematic to omit those: in fact, you might have to! Of course, you won't be able to make conclusions about the omitted ones.  Do you know this is the problem?

**Comment by coopergrace** [comment]
It looks like rows are the genomic windows, and columns are individuals. Either the windows have all PCA values, or they're all NAs, which would suggest that it's the windows that are the problem and not the individuals (I'm doubting myself as I write this however).

I'm not bothered if there are windows without any PCA values, in fact I assumed that some regions wouldn't be valuable for certain analyses. I saw your software cited in a paper and thought it was a really interesting approach.

**Comment by petrelharp** [comment]
Seems like those windows need to be omitted; do you see how to make this happen?

**Comment by rosehuang24** [comment]
hi guys, I wonder if there is a good solution to this as I encountered the same error message
```
Error in cmdscale(pc.distmat[!na.inds, !na.inds], k = opt$nmds) : 
NA values not allowed in 'd'
Calls: cbind -> cmdscale
```

I suspected that 
line173 ```na.inds <- is.na( all.pcas[,1] )``` and 
line177 ```cmdscale( pc.distmat[!na.inds,!na.inds], k=opt$nmds )[ ifelse( na.inds, NA, cumsum(!na.inds) ), ]``` 
from the ```run_lostruct.R``` script could be the problem (or not, I am a new learner to coding stuff) and I tried play with the code but can't see to fix this. 

I've also tested commands that do remove NA from a test matrix, but it never worked with the ```run_lostruct.R``` script. 

Any help would be greatly appreciated.

**Comment by petrelharp** [comment]
I think the *problem* is that there's too much missing data of some sort. The trick is to figure out why the missing data is messing things up, and make the script robust to it (or at least output a useful error message). If either of you can get me the data then I could get to the bottom of it.

**Comment by rosehuang24** [comment]
Hi,
thank you for the replay! I took a deeper look into the code after I posted my question here and tried to modify the original script. I managed to eliminated the error by removing windows with NAs, although as ugly as it seems in the script (sorry). However

**Comment by rosehuang24** [comment]
Hi,
Thank you for the replay! I took a deeper look into the code after I posted my question here and tried to modify the original script. I managed to eliminated the error by removing windows with NAs, although as ugly as it seems in the script (sorry). 

However, when it comes to ```summarize_run.Rmd```, some of the chromosomes had no data point on MDS2 despite of a normal-looking ```mds_coords.csv``` file. I am not sure if it is caused by my amateur script, hence here is [an example input and my running command](https://github.com/rosehuang24/temp_error_test). Together in this depository you can find the [script](https://github.com/rosehuang24/temp_error_test/blob/main/run_lostruct_customized.R) I edited (line153-167).

Thank you very much!

**Comment by petrelharp** [comment]
Ah ha. It looks like the problem is that many of your windows have no SNPs in them. Running this with longer windows (e.g. 100,000) has no problems (on my computer). Still, this ought to be able to run - I will look into that later - but, even if it does run, the number of SNPs per window will be very small, and so I would not expect much signal out of it. I recommend running with longer windows? (hopefully 10,000 works?) Or, fix your window size in SNPs?

**Comment by rosehuang24** [comment]
Hi Peter!

Thank you for your reply! I have tried window size of 10,000 and it works on some chromosomes (there are still a few chromosomes has NA problem but I believe it can be solved by increasing the window sizes. However considering the nature of my research object, I decided to try calculating windows by snps, and the mds calculations worked smoothly. Thanks again for your help!

**Comment by coopergrace** [comment]
I thought I'd fixed the issue by omitting windows with few (or no) SNPs, which calculated MDS for some chromosomes, but not all. 

So I switched to windows of SNPs (rather than bp), which again works for some chromosomes but not others. Smaller windows (e.g. 1000 SNPs) tend to work more often than larger ones, oddly enough. 

In `all.pcas` there are no lines with NA, NaN or Inf values. Therefore `na.inds <- is.na( all.pcas[,1] )` is all `FALSE`. Great.

However `pc.distmat <- pc_dist( all.pcas, npc=2 )` then results in a matrix of ~4000x4000, of which one column is NaN. I apparently can't omit this column (and corresponding row) because `(subscript) logical subscript too long` and of course the MDS calculation then fails with `NA values not allowed in 'd'`. My R translation skills aren't great, but is the issue the size of the chromosomes and resulting matrix? It's not the largest chromosomes that it's having issues with. I can send you the data if that will help.

**Comment by petrelharp** [comment]
Hm - yes, can you send me the data and the code you are running?

**Comment by rosehuang24** [comment]
Hi, 

Sorry again to bother you. For another project on fruit fly, it seems that running in window of snps (10 snps/window) still produces NA error for some of my contigs. 

[Here is the link ](https://github.com/rosehuang24/temp_error_test)to my code, data and the error message.  

Your help is much appreciated! Thank you. 

Rose

**Comment by rosehuang24** [comment]
Hi, 

I have solve the problem, and this message is for anyone who might encounter the same situation.

I found that line173 in [run_lostruct.R](https://github.com/petrelharp/local_pca/blob/master/templated/run_lostruct.R) removes the `NA` in _all.pcas_ but cannot take care of the `NaN` produced in the _pc.dismat_ calculation (line168). Take the above code as an example,  `all.pcas[11,1:3]`  gives us
```
 total lam_1 lam_2 
0     0     0 
```

With 0 as the denominator,  NaN will be produced and thus the error message. 

By changing line173 `na.inds <- is.na( all.pcas[,1] )` into `na.inds <- is.na( pc.distmat[,1] )` , the program will run smoothly.
