### ISSUE TITLE
Error in computing distances

### ISSUE THREAD

**Issue by zfuller5280** [petrelharp/local_pca#9]
I am using run_lostruct.R to run lostruct over 14 chromosomes contained in .bcf files contained in a directory `full_data/` with the following command:

```
Rscript run_lostruct.R -i full_data/ -t bp -s 5000 -I full_data/sample_info.tsv
```

It successfully finds PCs, however I am getting an error during the step when it computes distances between them. It returns the following after running for a fairly long time (I'm running with 120G of mem):

```
Error in pmax(0, (out + t(out))/2) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519
Calls: system.time -> pc_dist -> pmax
Timing stopped at: 1.484e+05 1505 1.502e+05
Execution halted
```

If I use a window size of 10kb or larger, it runs until completion. Is there a workaround or a solution to get this to run on a smaller window size? Thanks! Just let me know if you need any more information from my end.

**Comment by petrelharp** [comment]
Hm, that's too bad - if I interpret that right, it's failing at [this trivial step](https://github.com/petrelharp/local_pca/blob/6b7b4b43a5dee14fdb118cf79d3c5640497fb8df/lostruct/R/pc_dist.R#L35). I could add a flag that lets you skip that step, 

Two questions:
1. what version of R are you using?
2. how many windows of this size are there in the genome?

In my testing, I haven't been able to make `pmin( )` produce that error, even on a vector of length 1e9. (And, with 1e10 I ran out of memory with 120GB, but no error.) So I suspect that you're using an older version of R? And, if your distance matrix is so big that it runs into this error, you may want to check that you can actually do the next step with it.

**Comment by zfuller5280** [comment]
Correct, that is the step it is failing at I believe. The version of R I am using is 3.5.1, is this too old? There are total of 67955 windows of this size in the genome.

**Comment by petrelharp** [comment]
Ah, ok, that is a recent version of R and a bit of googling doesn't turn up a fix to this more recently. And, I can confirm the same behavior over here.  I've just pushed a change to this code which does the same thing without a `pmax( )`. Let me know if that fixes it (and close the issue if so?). Hopefully the MDS does not take too long...

Note that since [the script saves the PCAs it computes along the way](https://github.com/petrelharp/local_pca/blob/master/templated/run_lostruct.R#L120) running this again should not take as long as the first time.

**Comment by petrelharp** [comment]
The next step (MDS) doesn't look promising, from my testing (with 120GB of memory):
```
> x <- rep(1.0, 67955^2)
> dim(x) <- c(67955, 67955)
> x <- (x + t(x))/2
> x[x<0] <- 0
> z <- cmdscale(x, k=1)
Bus error (core dumped)
```
It *is* a wierd matrix (all 1.0) but I don't see how that would cause a bus error, so I'm more inclined to think it's the size of the matrix causing this to happen. Good luck. If R's `cmdscale( )` function doesn't work and you want to do something involving so many windows, then you can compute the distance matrix from the PCs as in `run_lostruct.R` and feed it to some other method.

**Comment by zfuller5280** [comment]
Thanks! The code without `pmax( )` seems to have fixed the issue. Closing for now.
